#Requires -Module @{ ModuleName = 'InvokeBuild'; ModuleVersion = '5.11.0' }

[CmdletBinding()]
param()

Set-StrictMode -Version Latest

$script:ModuleName = 'PSGraphRender'
$script:SrcRoot = Join-Path (Join-Path $BuildRoot 'src') $ModuleName
$script:OutRoot = Join-Path (Join-Path $BuildRoot 'output') $ModuleName
$script:ManifestPath = Join-Path $SrcRoot "$ModuleName.psd1"
$script:TestsRoot = Join-Path $BuildRoot 'tests'
$script:AnalyzerSettings = Join-Path $BuildRoot 'PSScriptAnalyzerSettings.psd1'

task Clean {
    if (Test-Path -LiteralPath (Join-Path $BuildRoot 'output')) {
        Remove-Item -LiteralPath (Join-Path $BuildRoot 'output') -Recurse -Force
    }
}

task Lint {
    # Rule configuration lives in PSScriptAnalyzerSettings.psd1 so editors and
    # CI lint identically to this task.
    $templateSets = Join-Path $SrcRoot 'TemplateSets'

    $results = @(
        Get-ChildItem -LiteralPath $SrcRoot -Directory |
            Where-Object { $_.FullName -ne $templateSets } |
            ForEach-Object { Invoke-ScriptAnalyzer -Path $_.FullName -Recurse -Settings $AnalyzerSettings }
    )
    $results += @(
        Get-ChildItem -LiteralPath $SrcRoot -File |
            ForEach-Object { Invoke-ScriptAnalyzer -Path $_.FullName -Settings $AnalyzerSettings }
    )

    # A backend's four data files are configuration, not a module manifest, and
    # PSMissingModuleManifestField cannot tell the difference - it fires on the
    # .psd1 extension alone. It reported a backend whose settings.psd1 is empty,
    # which is a legitimate thing for a backend with no behaviour to decide.
    #
    # Excluded HERE rather than in PSScriptAnalyzerSettings.psd1, so the rule
    # still guards the one file it is actually about: the module manifest.
    if (Test-Path -LiteralPath $templateSets) {
        $results += @(Invoke-ScriptAnalyzer -Path $templateSets -Recurse -Settings $AnalyzerSettings `
                -ExcludeRule PSMissingModuleManifestField)
    }

    if ($results) {
        $results | Format-Table -AutoSize | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $($results.Count) issue(s)."
    }
}

task Build Clean, {
    New-Item -ItemType Directory -Path $OutRoot -Force | Out-Null

    # Copy manifest
    Copy-Item -LiteralPath $ManifestPath -Destination (Join-Path $OutRoot "$ModuleName.psd1") -Force

    # Compose psm1 from private + public functions
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Auto-generated by PSGraphRender.build.ps1 — do not edit.')
    [void]$sb.AppendLine('Set-StrictMode -Version Latest')
    # Every source file is concatenated here at the module root, so $PSScriptRoot
    # differs from what the same code sees under the dev loader. Assets resolve
    # from $script:ModuleRoot in both. See Get-PSModuleGraphAsset.
    [void]$sb.AppendLine('$script:ModuleRoot = $PSScriptRoot')
    [void]$sb.AppendLine()

    $privateDir = Join-Path $SrcRoot 'Private'
    if (Test-Path -LiteralPath $privateDir) {
        # Recurse so Private/Html/*.ps1 is included. Sort by FullName, not Name,
        # so ordering is stable across subfolders.
        Get-ChildItem -Path $privateDir -Filter *.ps1 -File -Recurse | Sort-Object FullName | ForEach-Object {
            $relative = $_.FullName.Substring($privateDir.Length).TrimStart('\', '/')
            [void]$sb.AppendLine("# region $relative")
            [void]$sb.AppendLine((Get-Content -LiteralPath $_.FullName -Raw))
            [void]$sb.AppendLine("# endregion")
            [void]$sb.AppendLine()
        }
    }

    # Deliberately NOT recursive: the export list is derived from these
    # filenames, so Public/ must stay flat.
    $publicDir = Join-Path $SrcRoot 'Public'
    $publicNames = @()
    if (Test-Path -LiteralPath $publicDir) {
        Get-ChildItem -Path $publicDir -Filter *.ps1 -File | Sort-Object Name | ForEach-Object {
            $publicNames += [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
            [void]$sb.AppendLine("# region $($_.Name)")
            [void]$sb.AppendLine((Get-Content -LiteralPath $_.FullName -Raw))
            [void]$sb.AppendLine("# endregion")
            [void]$sb.AppendLine()
        }
    }

    if ($publicNames.Count -gt 0) {
        $exportList = ($publicNames | ForEach-Object { "'$_'" }) -join ', '
        [void]$sb.AppendLine("Export-ModuleMember -Function @($exportList)")
    }

    $outPsm1 = Join-Path $OutRoot "$ModuleName.psm1"
    [System.IO.File]::WriteAllText($outPsm1, $sb.ToString())

    # Copy any other root files (formats, types, etc.)
    Get-ChildItem -Path $SrcRoot -File | Where-Object {
        $_.Extension -notin @('.psd1', '.psm1') -and $_.Name -ne '.gitkeep'
    } | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $OutRoot $_.Name) -Force
    }

    # Copy the template sets. Each subdirectory is one rendering backend,
    # shipped as-is; there is no bundler. tests/Module.Quality.Tests.ps1 asserts
    # every file a templateset.psd1 names lands in the output.
    $templateSetsDir = Join-Path $SrcRoot 'TemplateSets'
    if (Test-Path -LiteralPath $templateSetsDir) {
        Copy-Item -LiteralPath $templateSetsDir -Destination $OutRoot -Recurse -Force
        $setCount = @(Get-ChildItem -Path (Join-Path $OutRoot 'TemplateSets') -Directory).Count
        $fileCount = @(Get-ChildItem -Path (Join-Path $OutRoot 'TemplateSets') -File -Recurse).Count
        Write-Build Green "  template sets: $setCount backend(s), $fileCount file(s)"
    }

    # Copy culture directories (en-US, fr-FR, ...) so Get-Help finds about_ topics.
    Get-ChildItem -Path $SrcRoot -Directory |
        Where-Object { $_.Name -match '^[a-z]{2}(-[A-Za-z]{2,4})?$' } |
        ForEach-Object {
            Copy-Item -LiteralPath $_.FullName -Destination $OutRoot -Recurse -Force
            Write-Build Green "  help: $($_.Name)"
        }

    Write-Build Green "Built $ModuleName -> $OutRoot"
}

task Test Build, {
    $pesterModule = Get-Module -Name Pester -ListAvailable |
        Where-Object { $_.Version -ge [version]'6.0.0' -and $_.Version -lt [version]'7.0.0' } |
        Sort-Object Version -Descending |
        Select-Object -First 1

    if (-not $pesterModule) {
        throw 'Pester 6.x is required. Run ./build.ps1 -Bootstrap'
    }

    Import-Module -Name $pesterModule.Path -Force

    $outputParent = Join-Path $BuildRoot 'output'

    $config = New-PesterConfiguration
    $config.Run.Path = $TestsRoot
    # Throw, not Exit: Run.Exit makes Pester call exit, which can terminate the
    # host process running the build. Throw raises inside InvokeBuild, which
    # fails the task properly and lets the rest of the build react.
    $config.Run.Throw = $true
    $config.Run.PassThru = $true
    $config.Output.Verbosity = 'Detailed'

    # Classic 'Should -Be' throws, so the suite cannot drift back to v5 style.
    $config.Should.DisableV5 = $true

    # PreTag tests are seals on a FINISHED iteration, not checks on work in
    # progress. The build should stay green while an iteration is half done;
    # the tag should not. ./build.ps1 -Task PreTag runs them.
    $config.Filter.ExcludeTag = 'PreTag'

    $config.TestResult.Enabled = $true
    $config.TestResult.OutputPath = Join-Path $outputParent 'testResults.xml'
    $config.TestResult.OutputFormat = 'NUnitXml'

    # Cover the built module, which is what the tests actually import.
    # CoverageGutters was removed in Pester 6 - do not add it back.
    $config.CodeCoverage.Enabled = $true
    $config.CodeCoverage.Path = Join-Path $OutRoot "$ModuleName.psm1"
    $config.CodeCoverage.OutputFormat = 'JaCoCo'
    $config.CodeCoverage.OutputPath = Join-Path $outputParent 'coverage.xml'
    # 70, against 71.56% measured when the renderer arrived. Deliberately just
    # under: the suite that came across with the code covers the transport and
    # config paths well and the document paths only through one fixture render,
    # so the honest number is the one the suite reaches rather than the one the
    # parent repository used. Raise it as tests arrive; see the ledger.
    $config.CodeCoverage.CoveragePercentTarget = 70

    # Ensure built module is preferred on PSModulePath for tests that Import-Module by name
    $env:PSModulePath = $outputParent + [System.IO.Path]::PathSeparator + $env:PSModulePath

    $result = Invoke-Pester -Configuration $config

    # CoveragePercentTarget only REPORTS. It has never once failed a run, and a
    # threshold nobody has seen fail is a threshold nobody knows works - this
    # sat at 74.88% against a target of 75 through three green builds. The
    # throw is the gate; the setting above is just the number it reads.
    $coverage = $result.CodeCoverage
    if ($coverage) {
        $percent = [math]::Round($coverage.CoveragePercent, 2)
        $target = $coverage.CoveragePercentTarget
        if ($percent -lt $target) {
            throw "Line coverage $percent% is below the target of $target%. Raise coverage, or lower the target deliberately and say so in the ledger."
        }
        Write-Build Green "Line coverage: $percent% (target $target%)"
    }
}

task PreTag Build, {
    # The gates that seal an iteration, run before `git tag -a` and not before
    # anything else. Deliberately a separate task rather than part of Test: a
    # half-finished iteration should still be able to run a green build, which
    # is most of what a build is for.
    $pesterModule = Get-Module -Name Pester -ListAvailable |
        Where-Object { $_.Version -ge [version]'6.0.0' -and $_.Version -lt [version]'7.0.0' } |
        Sort-Object Version -Descending |
        Select-Object -First 1

    if (-not $pesterModule) {
        throw 'Pester 6.x is required. Run ./build.ps1 -Bootstrap'
    }

    Import-Module -Name $pesterModule.Path -Force

    $config = New-PesterConfiguration
    $config.Run.Path = $TestsRoot
    $config.Run.Throw = $true
    $config.Output.Verbosity = 'Detailed'
    $config.Should.DisableV5 = $true
    $config.Filter.Tag = 'PreTag'

    $env:PSModulePath = (Join-Path $BuildRoot 'output') + [System.IO.Path]::PathSeparator + $env:PSModulePath

    Invoke-Pester -Configuration $config
    Write-Build Green 'Pre-tag gates passed. Safe to tag.'
}

task Import Build, {
    $manifest = Join-Path $OutRoot "$ModuleName.psd1"
    Import-Module -Name $manifest -Force -Verbose
}

task . Clean, Lint, Build, Test
